port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

proxies:
  - name: "Oracle_Server"
    type: vmess
    server: 143.47.236.12
    port: 10007
    uuid: 26e329ab-e5ca-4eb9-ab75-3177c31650b6
    alterId: 0
    cipher: auto
    udp: true
    network: ws
    ws-opts:
      path: /ray

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - Oracle_Server

rules:
  - MATCH,PROXY
